/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutFindImport } from './routes/_layout/find'
import { Route as LayoutCreateImport } from './routes/_layout/create'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutUsersUserSerIdImport } from './routes/_layout/users.$userSerId'
import { Route as LayoutPostPostSerIdImport } from './routes/_layout/post.$postSerId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFindRoute = LayoutFindImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCreateRoute = LayoutCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUsersUserSerIdRoute = LayoutUsersUserSerIdImport.update({
  id: '/users/$userSerId',
  path: '/users/$userSerId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPostPostSerIdRoute = LayoutPostPostSerIdImport.update({
  id: '/post/$postSerId',
  path: '/post/$postSerId',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/create': {
      id: '/_layout/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof LayoutCreateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/find': {
      id: '/_layout/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof LayoutFindImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/post/$postSerId': {
      id: '/_layout/post/$postSerId'
      path: '/post/$postSerId'
      fullPath: '/post/$postSerId'
      preLoaderRoute: typeof LayoutPostPostSerIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/users/$userSerId': {
      id: '/_layout/users/$userSerId'
      path: '/users/$userSerId'
      fullPath: '/users/$userSerId'
      preLoaderRoute: typeof LayoutUsersUserSerIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutCreateRoute: typeof LayoutCreateRoute
  LayoutFindRoute: typeof LayoutFindRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPostPostSerIdRoute: typeof LayoutPostPostSerIdRoute
  LayoutUsersUserSerIdRoute: typeof LayoutUsersUserSerIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutCreateRoute: LayoutCreateRoute,
  LayoutFindRoute: LayoutFindRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPostPostSerIdRoute: LayoutPostPostSerIdRoute,
  LayoutUsersUserSerIdRoute: LayoutUsersUserSerIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof LayoutAboutRoute
  '/create': typeof LayoutCreateRoute
  '/find': typeof LayoutFindRoute
  '/': typeof LayoutIndexRoute
  '/post/$postSerId': typeof LayoutPostPostSerIdRoute
  '/users/$userSerId': typeof LayoutUsersUserSerIdRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof LayoutAboutRoute
  '/create': typeof LayoutCreateRoute
  '/find': typeof LayoutFindRoute
  '/': typeof LayoutIndexRoute
  '/post/$postSerId': typeof LayoutPostPostSerIdRoute
  '/users/$userSerId': typeof LayoutUsersUserSerIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/create': typeof LayoutCreateRoute
  '/_layout/find': typeof LayoutFindRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/post/$postSerId': typeof LayoutPostPostSerIdRoute
  '/_layout/users/$userSerId': typeof LayoutUsersUserSerIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/signup'
    | '/about'
    | '/create'
    | '/find'
    | '/'
    | '/post/$postSerId'
    | '/users/$userSerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/about'
    | '/create'
    | '/find'
    | '/'
    | '/post/$postSerId'
    | '/users/$userSerId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/about'
    | '/_layout/create'
    | '/_layout/find'
    | '/_layout/'
    | '/_layout/post/$postSerId'
    | '/_layout/users/$userSerId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login",
        "/signup"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/create",
        "/_layout/find",
        "/_layout/",
        "/_layout/post/$postSerId",
        "/_layout/users/$userSerId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/create": {
      "filePath": "_layout/create.tsx",
      "parent": "/_layout"
    },
    "/_layout/find": {
      "filePath": "_layout/find.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/post/$postSerId": {
      "filePath": "_layout/post.$postSerId.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/$userSerId": {
      "filePath": "_layout/users.$userSerId.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
